### ISSUE TITLE
Menu desaparecer quando clicar em link

### ISSUE THREAD

**Issue by coelhotopetudo** [ftslorgbr/ftslorgbr.github.io#12]
No mobile - quando na index.html, acessar convidados e depois noticia. A página é carregada, mas atrás do menu, uma vez que esse não desaparece. 

Pode ser por estar no mesmo arquivo, referenciado por #convidados ou #noticias

**Comment by JonesBalada** [comment]
O código da versão 2016 não está mais nesse repositório.
