### ISSUE TITLE
Parte de patrocínio

### ISSUE THREAD

**Issue by coelhotopetudo** [ftslorgbr/ftslorgbr.github.io#15]
Hoje a parte de patrocínio só é acessada pelo drupal (http://ftsl.org.br/patrocinio).

**Comment by coelhotopetudo** [comment]
Ainda existe para o /patrocinio, mas todos os links apontam para 2016/patrocinio. Ideal seria unificar isso para não termos duplicidade da info.

**Comment by coelhotopetudo** [comment]
Fechei indevidamente.

**Comment by JonesBalada** [comment]
Já foi resolvido.
