### ISSUE TITLE
Utilizar a mesma seção realização/apoio/patrocinio nos dois lugares que essa aparece

### ISSUE THREAD

**Issue by coelhotopetudo** [ftslorgbr/ftslorgbr.github.io#17]
Na página principal. Pois hoje estamos tendo que alterar em dois lugares e o Caimi falou que pode-se incluir uma página via jquery, parece que assim que foi feito com o menu.

**Comment by caimi** [comment]
alteração efetuada. agora existe um arquivo chamado logo.html. Ele é incluido via javascript (init.js) nos locais indicados no html.
