### ISSUE TITLE
Não manter Cache no navegador

### ISSUE THREAD

**Issue by coelhotopetudo** [ftslorgbr/ftslorgbr.github.io#19]
Assegurar que o site não está ajustando o navegador a manter cache da página.

**Comment by coelhotopetudo** [comment]
Aconteceu com a Sueli que acessou o site recentemente e hoje não aparecia para ela o link para programação.

**Comment by coelhotopetudo** [comment]
Feito

**Comment by coelhotopetudo** [comment]
Menu (menu.html) não atualizou, fiz alteração nesse hoje, será que esse precisa de configuração de cache?

**Comment by JonesBalada** [comment]
- O código da versão 2016 não está mais nesse repositório.
