### ISSUE TITLE
Texto sobre como ajudar o site do FTSL

### ISSUE THREAD

**Issue by JonesBalada** [ftslorgbr/ftslorgbr.github.io#35]

**Comment by KalilNdM** [comment]
Como o FTSL ainda não é totalmente conhecido pela região, muitos curiosos são atraídos para descobrir do que se trata o mesmo. Para isso, um modelo único de página com pequenos resumos e descrições seria insuficiente para alguém motivado pela curiosidade e interesse, assim como para um conhecedor que gostaria de participar do fórum. Organizar cada tópico em que direcionaria para uma página específica com textos informativos e outros assuntos que talvez sejam do mesmo interesse de quem a acessou poderiam não só facilitar o entendimento do leitor, mas também agilizar a adesão de um possível participante do fórum. É importante separar os assuntos para que não confunda o leitor, muito menos faça-o perder o interesse. 

*Embora pouco conhecido do público em geral, o FTSL chama a atenção por se tratar de um evento anual direcionado a qualquer pessoa interessada em informática.  Para isso, um modelo único de página com pequenos resumos e descrições seria insuficiente para os interessados em participar do fórum. Organizar cada tópico em que direcionaria para uma página específica com textos informativos e outros assuntos que facilitem o entendimento do internauta, como também agilizar a sua adesão ao evento.

**Comment by JonesBalada** [comment]
Obrigado pela sugestão, mas seguindo sugestão do Flávio, o texto de ajuda sobre como colaborar com a parte estática do site do FTSL ficará no CONTRIBUTING.MD
