### ISSUE TITLE
Leiaute apoio e patrocinadores

### ISSUE THREAD

**Issue by JonesBalada** [ftslorgbr/ftslorgbr.github.io#37]
Ajustar pois o apoio está aparecendo na parte esquerda.

**Comment by caimi** [comment]
a ideia foi colocar um em cada linha mesmo
Realizacao
Apoio
Patrocinadores

Quando comecar a ter muitos logos fica melhor organizado

**Comment by JonesBalada** [comment]
Caimi já fez a alteração.
