### ISSUE TITLE
SEO descrição do evento quando pesquisado no Google

### ISSUE THREAD

**Issue by JonesBalada** [ftslorgbr/ftslorgbr.github.io#39]
Ajustar pois está mostrando o countdown, está como:

IX FÓRUM DE TECNOLOGIA EM SOFTWARE LIVRE. de 27 a 29 de setembro. prepare-se. Dias. 1. 1. 1. 1. 4. 4. 5. 5. 1. 1. 2. 2. Horas. 1. 1. 1. 1. 5. 5. 4. 4. Minutos.

**Comment by caimi** [comment]
inclui o meta description. vamos ver se indexa.
