### ISSUE TITLE
Páginas amigas

### ISSUE THREAD

**Issue by JonesBalada** [ftslorgbr/ftslorgbr.github.io#42]
Para reativar as páginas amigas do site:

- Favor colocar um link apontando para http://ftsl.org.br/participar-paginas-amigas.html para outros sites/páginas que desejarem participar;
- Colocar as imagens abaixo: 
- [![grupo](https://cloud.githubusercontent.com/assets/24393164/26354873/e0347a88-3f9c-11e7-873a-626faa302f61.png)](http://www.pentahobrasil.com.br)
- [![Curitiba Livre](https://cloud.githubusercontent.com/assets/24393164/26356902/01893884-3fa4-11e7-91f5-213a8c9c6b53.png)](http://curitibalivre.org.br)
- [![Debian Brasil](https://cloud.githubusercontent.com/assets/24393164/26356961/3926babe-3fa4-11e7-9b1e-4ae224a41350.png)](http://debianbrasil.org.br)

**Comment by JonesBalada** [comment]
Favor colocar um link apontando para http://ftsl.org.br/participar-paginas-amigas.html para outros sites/páginas que desejarem participar

**Comment by JonesBalada** [comment]
Opa Caimi, mais uma, estou perguntando se devemos colocar link.

![PHP Paraná](https://cloud.githubusercontent.com/assets/24393164/26361389/3e394708-3fb1-11e7-85f8-e76bb7e748f2.png)

**Comment by JonesBalada** [comment]
[![GruPy-PR](https://cloud.githubusercontent.com/assets/24393164/26365955/9e610f2c-3fbf-11e7-83b9-2fe30d602525.png)](https://grupypr.github.io)

**Comment by caimi** [comment]
inclui o carrossel. se padronizar o tamanho das logos fica melhor.

**Comment by JonesBalada** [comment]
Transformei para include e coloquei lah na pagina como participar, favor ajustar lah paa que as imagens apareceram umas ao lado das outras.

**Comment by JonesBalada** [comment]
Abrirei outra issue para fazer o ajuste mencionado acima.
