### ISSUE TITLE
Não tem código de conduta!

### ISSUE THREAD

**Issue by rsip22** [ftslorgbr/ftslorgbr.github.io#46]
Como querem que a pessoa sequer considere submeter atividade?!

**Comment by coelhotopetudo** [comment]
Seria algo como foi feito em 2014 no link abaixo?

http://sistema.ftsl.org.br/2014/politica-anti-assedio

**Comment by rsip22** [comment]
Isso. Lembrando que a organização precisa estar preparada para colocá-lo em efeito.

**Comment by JonesBalada** [comment]
Foi publicada nossa política antiassédio. 

Por favor ajude-nos verificando se está tudo certo e se quiser colaborar, basta editar o arquivo https://github.com/ftslorgbr/ftslorgbr.github.io/blob/master/politica-anti-assedio.md

**Comment by JonesBalada** [comment]
Acessível por http://ftsl.org.br/politica-anti-assedio.html 

Foi colocado link "Mapa do site" (estamos repensando o menu por este ter tamanho limitado) e também no sistema de envio de propostas.
