### ISSUE TITLE
Remover chamada de trabalhos (c4p)

### ISSUE THREAD

**Issue by JonesBalada** [ftslorgbr/ftslorgbr.github.io#55]
A c4p foi ateh dia 15jul, favor remover do site:

- mudar o botão ao lado do contador para apontar para o envolva-se;
- remover do menu o link para chamada de trabalhos; e 
- remover secao abaixo do contador.

**Comment by fgsl** [comment]
Resolvido pelo commit https://github.com/ftslorgbr/ftslorgbr.github.io/commit/c0c39e0666d5d60655d9d51fb0c8cb4e31c34474
