### ISSUE TITLE
CVD Fernao Vellozo

### ISSUE THREAD

**Issue by JonesBalada** [ftslorgbr/ftslorgbr.github.io#75]
![_100x100](https://user-images.githubusercontent.com/24393164/29936921-37752dcc-8e5a-11e7-8058-a14f2478100a.png)
![_normal](https://user-images.githubusercontent.com/24393164/29936923-38e7c78c-8e5a-11e7-8394-9535c253cb81.png)

**Comment by JonesBalada** [comment]
https://github.com/ftslorgbr/ftslorgbr.github.io/wiki/Convidados

**Comment by caimi** [comment]
fotos incluidas
