### ISSUE TITLE
Convidados (responsividade)

### ISSUE THREAD

**Issue by coelhotopetudo** [ftslorgbr/ftslorgbr.github.io#9]
Acontece qdo resolução 1.132×871 pixels

![convidados-responsividade-captura de tela de 2016-06-27 15 14 29](https://cloud.githubusercontent.com/assets/5190018/16390583/e2e68be4-3c79-11e6-8420-04d3a7d58982.png)

**Comment by JonesBalada** [comment]
O código da versão 2016 não está mais nesse repositório.
